# config/services.yml
# Add this to register your services
services:
    api.error:
        class: AppBundle\Utils\ApiError
        arguments: ['@translator']
        public: false
        
    app.mailer:
        class: AppBundle\Utils\Mailer
        arguments: ['@mailer']
        public: false
        
    AppBundle\Utils\Checker:
        public: false
        
    AppBundle\Utils\FilterProcessor:
        public: false
        
    AppBundle\Utils\FileUrler:
        arguments: ['@vich_uploader.templating.helper.uploader_helper']
        public: false
